apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontendapp
  template:
    metadata:
      labels:
        app: frontendapp
    spec:
      containers:
      - name: frontendapp
        image: frontendimage:latest
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
